/* 
https://www.iconfinder.com/icons/1243689/call_phone_icon
Creative Commons (Attribution 3.0 Unported);
https://www.iconfinder.com/Makoto_msk */

export const storeProducts = [
  {
    id: 1,
    title: "Acoustic Guitar",
    img: "img/product-1.png",
    price: 110,
    company: "Givson",
    info: "One of the most captivating aspects of the acoustic guitar is its ability to produce sounds without the need for amplification or electricity. This allows musicians to take their music anywhere, making it an ideal instrument for performances, gatherings, campfires, and more.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Classical Guitar",
    img: "img/product-2.png",
    price: 120,
    company: "Yamaha",
    info: "Classical guitar, also known as the nylon-string guitar or Spanish guitar, is a sophisticated and elegant instrument with a rich history that dates back centuries. Renowned for its warm, mellow tones and expressive capabilities, the classical guitar is deeply rooted in the traditions of classical and flamenco music.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Ukulele",
    img: "img/product-3.png",
    price: 75,
    company: "Vogga",
    info: "The ukulele, a small and charming instrument, has gained immense popularity worldwide for its cheerful sound and portability. Originating from Hawaii in the 19th century, the ukulele is part of the guitar family and has become synonymous with happiness, relaxation, and a laid-back island vibe.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Bass guitar",
    img: "img/product-4.png",
    price: 215,
    company: "Squier",
    info: "The bass guitar, an essential component of modern music, provides the backbone of rhythm and harmony in many musical genres. As a member of the guitar family, the bass guitar is known for its deep and resonant tones, responsible for anchoring the rhythm section and giving music its groove and foundation.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Electric guitar",
    img: "img/product-5.png",
    price: 299,
    company: "Washburn",
    info: "The electric guitar, an iconic instrument that revolutionized the world of music, is synonymous with energy, passion, and innovation. It emerged in the early 20th century as a response to the need for louder and more versatile instruments in the context of larger bands and evolving musical styles.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Mandolin",
    img: "img/product-6.png",
    price: 99,
    company: "Fender",
    info: "The mandolin, a delightful and distinctive instrument, holds a special place in the world of music. With its unique timbre and versatility, the mandolin has enchanted audiences across various cultures and genres, from traditional folk music to classical, bluegrass, and even rock.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Bandurria",
    img: "img/product-7.png",
    price: 85,
    company: "Fender",
    info: "The bandurria is a captivating and traditional stringed instrument, known for its rich history and distinct sound. It belongs to the lute family and is commonly found in Spanish and Latin American music, particularly in regions like Spain, the Philippines, and Peru.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Banjo",
    img: "img/product-8.png",
    price: 91,
    company: "Gold Tone",
    info: "The banjo is a fascinating and distinctive musical instrument with a rich history deeply rooted in American culture. Evoking images of folk music, bluegrass gatherings, and country songs, the banjo's twangy and rhythmic sound has become an iconic symbol of American musical heritage.",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 1,
  title: "Acoustic Guitar",
  img: "img/product-1.png",
  price: 110,
  company: "Givson",
  info: "One of the most captivating aspects of the acoustic guitar is its ability to produce sounds without the need for amplification or electricity. This allows musicians to take their music anywhere, making it an ideal instrument for performances, gatherings, campfires, and more.",
  inCart: false,
  count: 0,
  total: 0,
};
